In [1]:
import numpy as np

In [3]:
list = ['1','2','3','4','5']

In [5]:
array_list = np.array(object = list)

In [7]:
type(list)

list

In [9]:
type(array_list)

numpy.ndarray

In [11]:
# There is a difference in the type as one of them is an array and the other is a list

## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [16]:
for i in range(len(list)):
    print(type(list[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [20]:
for i in range(len(array_list)):
    print(type(array_list[i]))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:

In [23]:
array_list = np.array(object = list,dtype = int)

In [25]:
array_list

array([1, 2, 3, 4, 5])

In [27]:
for i in range(len(list)):
    print(type(list[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [29]:
for i in range(len(array_list)):
    print(type(array_list[i]))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [31]:
## There is a difference in the datatype as one is a string and other is an int

## Q4. Write a code to find the following characteristics of variable, num_array:

In [34]:
import numpy as np
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object = num_list)

In [36]:
num_array.shape

(2, 3)

In [38]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [51]:
arr =np.fromfunction(lambda i,j:0*(i+j), (3,3))

In [53]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
## Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [61]:
arr1 = np.diag([1,1,1,1,1])

In [63]:
arr1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])